name: Kubernetes Deployment

on:
  workflow_call:
    inputs:
      service_account:
        description: 'service account name'
        required: true
        type: string
      aws_region:
        description: 'AWS Region to deploy'
        required: true
        type: string
      k8s_namespace:
        description: 'namespace for K8s deployment'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Deploy to Kubernetes
        if: (( github.ref == 'refs/heads/main' || github.ref == 'main' ) &&  github.event.pull_request.merged == true )
        run: |
          kubectl apply -f path/to/your/deployment.yaml -n ${{ inputs.k8s_namespace }}